services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./mongo:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - dominios_net

networks:
  dominios_net:
    external: true